// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.5-bufbuild-protocompile-easyp
// source: api/dns/v1/dns.proto

package dnsv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_api_dns_v1_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dns_v1_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_api_dns_v1_dns_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_api_dns_v1_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dns_v1_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_dns_v1_dns_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_dns_v1_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dns_v1_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_dns_v1_dns_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

var File_api_dns_v1_dns_proto protoreflect.FileDescriptor

const file_api_dns_v1_dns_proto_rawDesc = "" +
	"\n" +
	"\x14api/dns/v1/dns.proto\x12\x06dns.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"%\n" +
	"\n" +
	"AddRequest\x12\x17\n" +
	"\x02ip\x18\x01 \x01(\tB\a\xfaB\x04r\x02p\x01R\x02ip\"(\n" +
	"\rRemoveRequest\x12\x17\n" +
	"\x02ip\x18\x01 \x01(\tB\a\xfaB\x04r\x02p\x01R\x02ip\" \n" +
	"\fListResponse\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips2\xae\x01\n" +
	"\n" +
	"DnsService\x121\n" +
	"\x03Add\x12\x12.dns.v1.AddRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x06Remove\x12\x15.dns.v1.RemoveRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x14.dns.v1.ListResponseB3Z1github.com/domovonok/dns-manager/api/dns/v1;dnsv1b\x06proto3"

var (
	file_api_dns_v1_dns_proto_rawDescOnce sync.Once
	file_api_dns_v1_dns_proto_rawDescData []byte
)

func file_api_dns_v1_dns_proto_rawDescGZIP() []byte {
	file_api_dns_v1_dns_proto_rawDescOnce.Do(func() {
		file_api_dns_v1_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_dns_v1_dns_proto_rawDesc), len(file_api_dns_v1_dns_proto_rawDesc)))
	})
	return file_api_dns_v1_dns_proto_rawDescData
}

var file_api_dns_v1_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_dns_v1_dns_proto_goTypes = []any{
	(*AddRequest)(nil),    // 0: dns.v1.AddRequest
	(*RemoveRequest)(nil), // 1: dns.v1.RemoveRequest
	(*ListResponse)(nil),  // 2: dns.v1.ListResponse
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_api_dns_v1_dns_proto_depIdxs = []int32{
	0, // 0: dns.v1.DnsService.Add:input_type -> dns.v1.AddRequest
	1, // 1: dns.v1.DnsService.Remove:input_type -> dns.v1.RemoveRequest
	3, // 2: dns.v1.DnsService.List:input_type -> google.protobuf.Empty
	3, // 3: dns.v1.DnsService.Add:output_type -> google.protobuf.Empty
	3, // 4: dns.v1.DnsService.Remove:output_type -> google.protobuf.Empty
	2, // 5: dns.v1.DnsService.List:output_type -> dns.v1.ListResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_dns_v1_dns_proto_init() }
func file_api_dns_v1_dns_proto_init() {
	if File_api_dns_v1_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_dns_v1_dns_proto_rawDesc), len(file_api_dns_v1_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dns_v1_dns_proto_goTypes,
		DependencyIndexes: file_api_dns_v1_dns_proto_depIdxs,
		MessageInfos:      file_api_dns_v1_dns_proto_msgTypes,
	}.Build()
	File_api_dns_v1_dns_proto = out.File
	file_api_dns_v1_dns_proto_goTypes = nil
	file_api_dns_v1_dns_proto_depIdxs = nil
}
